//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILM()
        {
            this.FILM_ACTOR = new HashSet<FILM_ACTOR>();
            this.FILM_CATEGORY = new HashSet<FILM_CATEGORY>();
            this.INVENTORY = new HashSet<INVENTORY>();
        }
    
        public decimal FILM_ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string RELEASE_YEAR { get; set; }
        public decimal LANGUAGE_ID { get; set; }
        public Nullable<decimal> ORIGINAL_LANGUAGE_ID { get; set; }
        public decimal RENTAL_DURATION { get; set; }
        public decimal RENTAL_RATE { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public decimal REPLACEMENT_COST { get; set; }
        public string RATING { get; set; }
        public string SPECIAL_FEATURES { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILM_ACTOR> FILM_ACTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILM_CATEGORY> FILM_CATEGORY { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual LANGUAGE LANGUAGE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY> INVENTORY { get; set; }
    }
}
