//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY()
        {
            this.RENTAL = new HashSet<RENTAL>();
        }
    
        public decimal INVENTORY_ID { get; set; }
        public decimal FILM_ID { get; set; }
        public decimal STORE_ID { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
    
        public virtual FILM FILM { get; set; }
        public virtual STORE STORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL> RENTAL { get; set; }
    }
}
