//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public decimal PAYMENT_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal STAFF_ID { get; set; }
        public Nullable<decimal> RENTAL_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual RENTAL RENTAL { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
