//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENTAL()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
        }
    
        public decimal RENTAL_ID { get; set; }
        public System.DateTime RENTAL_DATE { get; set; }
        public decimal INVENTORY_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public decimal STAFF_ID { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual INVENTORY INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
