//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SakilaEntities : DbContext
    {
        public SakilaEntities()
            : base("name=SakilaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTOR> ACTOR { get; set; }
        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<FILM> FILM { get; set; }
        public virtual DbSet<FILM_ACTOR> FILM_ACTOR { get; set; }
        public virtual DbSet<FILM_CATEGORY> FILM_CATEGORY { get; set; }
        public virtual DbSet<FILM_TEXT> FILM_TEXT { get; set; }
        public virtual DbSet<INVENTORY> INVENTORY { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGE { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<RENTAL> RENTAL { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<STORE> STORE { get; set; }
    }
}
